### ISSUE TITLE
Does not compile on windows

### ISSUE THREAD

**Issue by Kulitorum** [sephirot47/BSPOpenGL#1]
I really wanted this to work, but I get 1100 errors...

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\cmath:19: error: C2039: 'acosf': is not a member of '`global namespace''

in <cmath>

_Check_return_ inline float acos(_In_ float _Xx) _NOEXCEPT
	{
	return (_CSTD acosf(_Xx));
	}

Any idea how to fix?

**Comment by sephirot47** [comment]
Ye...this was compiled with g++, guess you will have to change some stuff to get it working with MSVC, my bad! But these errors should be easily fixable. In this case, it may work if you include <math.h> to make it work (it is searching "acosf" in global namespace, so I guess you have to include the old math.h header, instead of cmath which wraps functions under the std namespace). Hope it works!
